FROM nvcr.io/nvidia/tritonserver:24.03-pyt-python-py3
LABEL author.name="Mingzhi Zheng"
LABEL author.email="stevezheng23@gmail.com"

RUN pip --no-cache-dir install transformers

COPY model_repository /model_repository
