name: "word"
backend: "python"
max_batch_size : 0
input [
  {
    name: "text"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
output [
  {
    name: "text"
    data_type: TYPE_STRING
    dims: [ -1 ]
  },
  {
    name: "offset"
    data_type: TYPE_INT32
    dims: [ -1 ]
  },
  {
    name: "length"
    data_type: TYPE_INT32
    dims: [ -1 ]
  },
  {
    name: "index"
    data_type: TYPE_INT32
    dims: [ -1 ]
  },
  {
    name: "group_index"
    data_type: TYPE_INT32
    dims: [ -1 ]
  }
]
instance_group [
  {
    kind: KIND_CPU
  }
]