name: "generate"
backend: "python"
max_batch_size : 0
input [
  {
    name: "messages"
    data_type: TYPE_STRING
    dims: [ -1 ]
  },
  {
    name: "arguments"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
output [
  {
    name: "results"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
instance_group [
  {
    kind: KIND_CPU
  }
]